# Generated by Django 3.0.5 on 2020-12-19 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='date_from',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2020)], verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='date_to',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2020)], verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
    ]
