# Generated by Django 3.0.5 on 2020-12-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201219_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200, verbose_name='Цитата')),
                ('lemmed_line', models.CharField(db_index=True, max_length=200, verbose_name='Леммизированная цитата')),
                ('poem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citate', to='api.Poem', verbose_name='Цитата')),
            ],
        ),
    ]
