# Generated by Django 3.0.5 on 2020-12-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_citate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citate',
            options={'verbose_name': 'Цитата', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterField(
            model_name='citate',
            name='poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citate', to='api.Poem', verbose_name='Произведение'),
        ),
    ]
