# Generated by Django 3.0.5 on 2020-12-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201219_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citate',
            name='lemmed_line',
            field=models.CharField(db_index=True, max_length=5000, verbose_name='Леммизированная цитата'),
        ),
        migrations.AlterField(
            model_name='citate',
            name='line',
            field=models.CharField(max_length=5000, verbose_name='Цитата'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.CharField(db_index=True, max_length=5000, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='name',
            field=models.CharField(db_index=True, max_length=5000, verbose_name='Название'),
        ),
    ]
